schema_version = "1.0.0"

id = "gititdone"
version = "0.0.1"
name = "GitItDone"
tagline = "Git in Blender"
maintainer = "Nicolas Predella"
type = "add-on"

# website = "https://github.com/PredellaN/GitItDone"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# Other supported platforms: "windows-arm64", "macos-x64"

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
  "./wheels/gitpython-3.1.45-py3-none-any.whl",
  "./wheels/gitdb-4.0.12-py3-none-any.whl",
  "./wheels/smmap-5.0.2-py3-none-any.whl",
]

[permissions]
network = "Using GIT"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "experimental/",
  "cache/",
]